"""create_sale_documents_table

Revision ID: 695ece4edc35
Revises: ca3edc500f37
Create Date: 2026-07-11 09:57:22.493258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695ece4edc35'
down_revision: Union[str, Sequence[str], None] = 'ca3edc500f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('full_number', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('whatsapp_sent', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('whatsapp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_documents_document_type'), 'sale_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_sale_documents_full_number'), 'sale_documents', ['full_number'], unique=True)
    op.create_index(op.f('ix_sale_documents_id'), 'sale_documents', ['id'], unique=False)
    op.create_index(op.f('ix_sale_documents_number'), 'sale_documents', ['number'], unique=False)
    op.create_index(op.f('ix_sale_documents_sale_id'), 'sale_documents', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_documents_serie'), 'sale_documents', ['serie'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_documents_serie'), table_name='sale_documents')
    op.drop_index(op.f('ix_sale_documents_sale_id'), table_name='sale_documents')
    op.drop_index(op.f('ix_sale_documents_number'), table_name='sale_documents')
    op.drop_index(op.f('ix_sale_documents_id'), table_name='sale_documents')
    op.drop_index(op.f('ix_sale_documents_full_number'), table_name='sale_documents')
    op.drop_index(op.f('ix_sale_documents_document_type'), table_name='sale_documents')
    op.drop_table('sale_documents')
    # ### end Alembic commands ###
