"""create_customer_debt_tables

Revision ID: ca3edc500f37
Revises: ff7ecc92199b
Create Date: 2026-07-09 13:44:23.880263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3edc500f37'
down_revision: Union[str, Sequence[str], None] = 'ff7ecc92199b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pending_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_debts_customer_id'), 'customer_debts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_debts_id'), 'customer_debts', ['id'], unique=False)
    op.create_index(op.f('ix_customer_debts_sale_id'), 'customer_debts', ['sale_id'], unique=True)
    op.create_table('customer_debt_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_debt_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_register_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ),
    sa.ForeignKeyConstraint(['customer_debt_id'], ['customer_debts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_debt_payments_customer_debt_id'), 'customer_debt_payments', ['customer_debt_id'], unique=False)
    op.create_index(op.f('ix_customer_debt_payments_id'), 'customer_debt_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_debt_payments_id'), table_name='customer_debt_payments')
    op.drop_index(op.f('ix_customer_debt_payments_customer_debt_id'), table_name='customer_debt_payments')
    op.drop_table('customer_debt_payments')
    op.drop_index(op.f('ix_customer_debts_sale_id'), table_name='customer_debts')
    op.drop_index(op.f('ix_customer_debts_id'), table_name='customer_debts')
    op.drop_index(op.f('ix_customer_debts_customer_id'), table_name='customer_debts')
    op.drop_table('customer_debts')
    # ### end Alembic commands ###
