"""create cash register tables

Revision ID: ff7ecc92199b
Revises: 2fe225b4a048
Create Date: 2026-07-09 12:50:02.070182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7ecc92199b'
down_revision: Union[str, Sequence[str], None] = '2fe225b4a048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_sales_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('yape_sales_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_sales_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('manual_income_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('manual_expense_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_cash_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted_cash_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_difference_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_yape_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confirmed_yape_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('yape_difference_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_sales_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_profit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('close_notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_registers_id'), 'cash_registers', ['id'], unique=False)
    op.create_index(op.f('ix_cash_registers_status'), 'cash_registers', ['status'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_register_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_cash_register_id'), 'cash_movements', ['cash_register_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_id'), 'cash_movements', ['id'], unique=False)
    op.create_index(op.f('ix_cash_movements_movement_type'), 'cash_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_cash_movements_payment_method'), 'cash_movements', ['payment_method'], unique=False)
    op.create_index(op.f('ix_cash_movements_reference_id'), 'cash_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_reference_type'), 'cash_movements', ['reference_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_movements_reference_type'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_reference_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_payment_method'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_movement_type'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_cash_register_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_cash_registers_status'), table_name='cash_registers')
    op.drop_index(op.f('ix_cash_registers_id'), table_name='cash_registers')
    op.drop_table('cash_registers')
    # ### end Alembic commands ###
